version: '3.9'

services:
  django:
    build: ./
    env_file:
      - .env
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      DJANGO_SETTINGS_MODULE: core.settings
      APP_PORT: 8000
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      GDAL_LIBRARY_PATH: ${GDAL_LIBRARY_PATH}
      GEOS_LIBRARY_PATH: ${GEOS_LIBRARY_PATH}
    volumes:
      - ./src:/app:Z
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - traefik_network
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"

      # HTTPS - apenas /admin e /api
      - "traefik.http.routers.django.rule=Host(`${DOMAIN}`) && (PathPrefix(`/admin`) || PathPrefix(`/api`))"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
      - "traefik.http.routers.django.priority=20"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
      - "traefik.http.routers.django.middlewares=gzip"

      # Redirecionamento HTTP → HTTPS
      - "traefik.http.routers.django-http.rule=Host(`${DOMAIN}`) && (PathPrefix(`/admin`) || PathPrefix(`/api`))"
      - "traefik.http.routers.django-http.entrypoints=web"
      - "traefik.http.routers.django-http.middlewares=redirect-to-https"

      # Middlewares
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.gzip.compress=true"

  db:
    image: postgis/postgis:14-3.3
    container_name: postgis
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  static:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`${DOMAIN}`) && (PathPrefix(`/static`) || PathPrefix(`/media`))"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls=true"
      - "traefik.http.services.static.loadbalancer.server.port=80"
      - "traefik.http.middlewares.static-headers.headers.customResponseHeaders.Cache-Control=max-age=31536000"

networks:
  traefik_network:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:


