# Generated by Django 5.1.7 on 2025-03-25 01:48

import cloudinary.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='city',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='state',
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Clique no mapa para selecionar a localização', null=True, srid=4326, verbose_name='Localização'),
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Foto do Animal',
                'verbose_name_plural': 'Fotos dos Animais',
            },
        ),
    ]
